### ISSUE TITLE
Partials inside a /partials/ or /partial/ subfolder don't work

### ISSUE THREAD

**Issue by parterburn** [aki77/vscode-rails-partial#5]
This one might be easier to see, so I put together a Loom here: https://www.loom.com/share/8e100c65ff98432f81e7aff6fbfb4929

Essentially, if you have your partials inside a subfolder named either `partial` or `partials` the jump-to-def doesn't work as expected. If you rename the folder to anything else, like `parts`, it works fine.

**Comment by johannesschobel** [comment]
stumbled upon the same issue here!

@aki77 can this be fixed please?

**Comment by aki77** [comment]
Fixed in v0.3.5!
